"""Prepare OpenBCI EEG exports for paradigm-based analysis.

The lecture PDF describes the minimum useful EEG data structure as:

1. continuous EEG data with known channels, units, sampling rate, and timing
2. an event table with onset, duration, code, condition, response, correctness
3. metadata about the subject/session/experiment and acquisition settings

This script turns the filtered OpenBCI CSV generated by filter_openbci_raw.py
into that structure. It can also merge a separate event log when one exists.
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


DEFAULT_FILTERED_DIR = Path("filtered_data")
DEFAULT_OUTPUT_DIR = Path("analysis_ready")
EVENT_COLUMNS = [
    "event_id",
    "onset_sample",
    "onset_time_s",
    "duration_s",
    "code",
    "condition",
    "trial",
    "response",
    "correct",
    "notes",
]


def parse_openbci_header(path: Path) -> dict[str, float | int | str]:
    info: dict[str, float | int | str] = {}
    if path.suffix.lower() != ".txt":
        return info

    with path.open("r", encoding="utf-8", errors="replace") as handle:
        for line in handle:
            if not line.startswith("%"):
                break
            if "Sample Rate" in line:
                match = re.search(r"=\s*([0-9.]+)", line)
                if match:
                    info["sample_rate_hz"] = float(match.group(1))
            elif "Number of channels" in line:
                match = re.search(r"=\s*([0-9]+)", line)
                if match:
                    info["channel_count"] = int(match.group(1))
            elif "Board" in line:
                info["board"] = line.split("=", 1)[-1].strip()
    return info


def find_latest_filtered_csv(filtered_dir: Path) -> Path:
    candidates = [
        path
        for path in filtered_dir.glob("*_filtered_*.csv")
        if path.is_file() and path.stat().st_size > 0
    ]
    if not candidates:
        raise FileNotFoundError(f"No *_filtered_*.csv file found under {filtered_dir}")
    return max(candidates, key=lambda path: path.stat().st_mtime)


def read_eeg_table(path: Path) -> tuple[pd.DataFrame, dict[str, Any]]:
    header = parse_openbci_header(path)
    if path.suffix.lower() == ".txt":
        frame = pd.read_csv(path, comment="%", skipinitialspace=True)
    else:
        frame = pd.read_csv(path, skipinitialspace=True)
    return frame, header


def pick_channel_columns(frame: pd.DataFrame) -> list[str]:
    filtered = [
        column
        for column in frame.columns
        if column.startswith("EXG Channel") and "filtered_uV" in column
    ]
    if filtered:
        return filtered

    raw = [
        column
        for column in frame.columns
        if column.startswith("EXG Channel") and "filtered_uV" not in column
    ]
    if raw:
        return raw

    raise ValueError("No EXG Channel columns were found in the input file.")


def infer_sample_rate(frame: pd.DataFrame, header: dict[str, Any], fallback: float) -> float:
    if "sample_rate_hz" in header:
        return float(header["sample_rate_hz"])

    inferred = fallback
    if "Timestamp" in frame.columns:
        timestamp = pd.to_numeric(frame["Timestamp"], errors="coerce")
        diffs = timestamp.diff().dropna()
        diffs = diffs[(diffs > 0) & np.isfinite(diffs)]
        if not diffs.empty:
            median_dt = float(diffs.median())
            if median_dt > 0:
                inferred = 1.0 / median_dt

    for common_rate in (125.0, 200.0, 250.0, 500.0, 1000.0, 2000.0):
        if abs(inferred - common_rate) / common_rate < 0.01:
            return common_rate
    return round(inferred, 6)


def normalize_continuous_eeg(
    frame: pd.DataFrame,
    channel_columns: list[str],
    sample_rate_hz: float,
) -> tuple[pd.DataFrame, pd.DataFrame, np.ndarray]:
    exg = frame[channel_columns].apply(pd.to_numeric, errors="coerce")
    valid_rows = ~exg.isna().all(axis=1)
    frame = frame.loc[valid_rows].reset_index(drop=True)
    exg = exg.loc[valid_rows].reset_index(drop=True)
    exg = exg.interpolate(limit_direction="both").fillna(0.0)

    channel_names = [f"Ch{index + 1:02d}" for index in range(len(channel_columns))]
    continuous = pd.DataFrame()
    continuous["sample"] = np.arange(len(exg), dtype=int)
    continuous["time_s"] = continuous["sample"] / sample_rate_hz
    if "Sample Index" in frame.columns:
        continuous["source_sample_index"] = pd.to_numeric(
            frame["Sample Index"], errors="coerce"
        ).to_numpy()

    if "Timestamp" in frame.columns:
        timestamp = pd.to_numeric(frame["Timestamp"], errors="coerce")
        timestamp = timestamp.interpolate(limit_direction="both")
        continuous["timestamp_offset_s"] = timestamp - timestamp.iloc[0]
        continuous["absolute_timestamp"] = timestamp

    for channel_name, source_column in zip(channel_names, channel_columns):
        continuous[channel_name] = exg[source_column].to_numpy(dtype=float)

    if "Timestamp (Formatted)" in frame.columns:
        continuous["timestamp_formatted"] = frame["Timestamp (Formatted)"].astype(str)

    channels = pd.DataFrame(
        {
            "channel_index": np.arange(1, len(channel_columns) + 1, dtype=int),
            "channel_name": channel_names,
            "source_column": channel_columns,
            "type": "EEG",
            "unit": "uV",
            "electrode_position": "",
            "reference": "",
            "status": "good",
            "notes": "",
        }
    )

    matrix = continuous[channel_names].to_numpy(dtype=float).T
    return continuous, channels, matrix


def read_events(path: Path | None, sample_rate_hz: float) -> pd.DataFrame:
    if path is None:
        return pd.DataFrame(columns=EVENT_COLUMNS)

    suffix = path.suffix.lower()
    if suffix in {".csv", ".txt"}:
        events = pd.read_csv(path)
    elif suffix == ".tsv":
        events = pd.read_csv(path, sep="\t")
    else:
        raise ValueError("Event log must be CSV, TSV, or TXT.")

    for column in EVENT_COLUMNS:
        if column not in events.columns:
            events[column] = ""

    if events["event_id"].eq("").all():
        events["event_id"] = np.arange(1, len(events) + 1, dtype=int)

    onset_sample = pd.to_numeric(events["onset_sample"], errors="coerce")
    onset_time = pd.to_numeric(events["onset_time_s"], errors="coerce")

    missing_sample = onset_sample.isna() & onset_time.notna()
    if missing_sample.any():
        events.loc[missing_sample, "onset_sample"] = np.rint(
            onset_time.loc[missing_sample] * sample_rate_hz
        ).astype(int)

    missing_time = onset_time.isna() & onset_sample.notna()
    if missing_time.any():
        events.loc[missing_time, "onset_time_s"] = (
            onset_sample.loc[missing_time] / sample_rate_hz
        )

    return events[EVENT_COLUMNS]


def make_metadata(
    input_path: Path,
    sample_rate_hz: float,
    continuous: pd.DataFrame,
    channels: pd.DataFrame,
    events: pd.DataFrame,
    args: argparse.Namespace,
    header: dict[str, Any],
) -> pd.DataFrame:
    duration_s = float(continuous["time_s"].iloc[-1]) if len(continuous) else 0.0
    timestamp_duration_s = (
        float(continuous["timestamp_offset_s"].iloc[-1])
        if "timestamp_offset_s" in continuous.columns and len(continuous)
        else ""
    )
    source_sample_span = ""
    missing_source_samples = ""
    if "source_sample_index" in continuous.columns and len(continuous):
        source_index = pd.to_numeric(continuous["source_sample_index"], errors="coerce")
        if source_index.notna().any():
            source_sample_span = int(source_index.max() - source_index.min())
            missing_source_samples = int(source_sample_span - (len(continuous) - 1))
    large_timestamp_gap_count = ""
    if "absolute_timestamp" in continuous.columns:
        timestamp = pd.to_numeric(continuous["absolute_timestamp"], errors="coerce")
        expected_dt = 1.0 / sample_rate_hz
        large_timestamp_gap_count = int((timestamp.diff() > expected_dt * 1.5).sum())

    values: dict[str, Any] = {
        "source_file": str(input_path.resolve()),
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "subject_id": args.subject_id,
        "session_id": args.session_id,
        "task_name": args.task_name,
        "sample_rate_hz": sample_rate_hz,
        "channel_count": len(channels),
        "sample_count": len(continuous),
        "sample_clock_duration_s": round(duration_s, 6),
        "timestamp_duration_s": (
            round(timestamp_duration_s, 6) if timestamp_duration_s != "" else ""
        ),
        "source_sample_span": source_sample_span,
        "missing_source_samples_estimate": missing_source_samples,
        "large_timestamp_gap_count": large_timestamp_gap_count,
        "unit": "uV",
        "continuous_orientation": "rows=samples, columns=channels",
        "matrix_orientation": "rows=channels, columns=samples",
        "event_count": len(events),
        "event_source": str(args.events.resolve()) if args.events else "missing/template",
        "reference": "",
        "filtering": "see source filename or preprocessing notes",
        "notes": (
            "Events are required for trial/epoch analysis. If this workbook has an empty "
            "events sheet, add stimulus/response markers from the experiment log."
        ),
    }
    values.update(header)
    return pd.DataFrame({"key": list(values.keys()), "value": list(values.values())})


def write_json(path: Path, metadata: pd.DataFrame) -> None:
    data = {str(row.key): row.value for row in metadata.itertuples(index=False)}
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def write_excel_workbook(
    path: Path,
    metadata: pd.DataFrame,
    channels: pd.DataFrame,
    events: pd.DataFrame,
    continuous: pd.DataFrame,
) -> None:
    readme = pd.DataFrame(
        {
            "item": [
                "continuous_eeg",
                "channels",
                "events",
                "metadata",
                "matrix_npz",
                "next_step",
            ],
            "meaning": [
                "Continuous EEG: one row per sample; Ch01... columns are EEG in uV.",
                "Channel map: fill electrode_position/reference/status before formal analysis.",
                "Event table: fill onset/duration/code/condition to cut trials or epochs.",
                "Acquisition and processing context.",
                "The NPZ file stores data_uv as channels x samples for Python analysis.",
                "For ERP/P300, SSVEP, MI, etc., merge real event markers before epoching.",
            ],
        }
    )

    with pd.ExcelWriter(path, engine="xlsxwriter") as writer:
        readme.to_excel(writer, sheet_name="README", index=False)
        metadata.to_excel(writer, sheet_name="metadata", index=False)
        channels.to_excel(writer, sheet_name="channels", index=False)
        events.to_excel(writer, sheet_name="events", index=False)
        continuous.to_excel(writer, sheet_name="continuous_eeg", index=False)

        workbook = writer.book
        header_format = workbook.add_format({"bold": True, "bg_color": "#D9EAF7"})
        for sheet_name, worksheet in writer.sheets.items():
            worksheet.freeze_panes(1, 0)
            worksheet.autofilter(0, 0, 0, max(0, worksheet.dim_colmax))
            for col in range(max(0, worksheet.dim_colmax) + 1):
                worksheet.write(0, col, worksheet.table[0][col].string, header_format)
            worksheet.set_column(0, max(0, worksheet.dim_colmax), 16)


def write_outputs(
    output_dir: Path,
    input_path: Path,
    metadata: pd.DataFrame,
    channels: pd.DataFrame,
    events: pd.DataFrame,
    continuous: pd.DataFrame,
    matrix: np.ndarray,
    sample_rate_hz: float,
) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    stem = input_path.stem.replace("_filtered_0p5-40Hz_notch50Hz", "")
    base = output_dir / f"{stem}_paradigm_ready"

    csv_path = base.with_name(f"{base.name}_continuous_eeg.csv")
    events_path = base.with_name(f"{base.name}_events.csv")
    channels_path = base.with_name(f"{base.name}_channels.csv")
    metadata_json_path = base.with_name(f"{base.name}_metadata.json")
    matrix_path = base.with_name(f"{base.name}_matrix_channels_x_samples.npz")
    workbook_path = base.with_suffix(".xlsx")

    continuous.to_csv(csv_path, index=False)
    events.to_csv(events_path, index=False)
    channels.to_csv(channels_path, index=False)
    write_json(metadata_json_path, metadata)
    np.savez_compressed(
        matrix_path,
        data_uv=matrix,
        channel_names=channels["channel_name"].to_numpy(dtype=str),
        sample_rate_hz=float(sample_rate_hz),
        time_s=continuous["time_s"].to_numpy(dtype=float),
    )
    write_excel_workbook(workbook_path, metadata, channels, events, continuous)
    return workbook_path, matrix_path


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create an EEG paradigm-ready workbook and matrix from OpenBCI data."
    )
    parser.add_argument("--input", type=Path, default=None, help="filtered CSV or OpenBCI RAW txt")
    parser.add_argument("--filtered-dir", type=Path, default=DEFAULT_FILTERED_DIR)
    parser.add_argument("--events", type=Path, default=None, help="optional event log CSV/TSV/TXT")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--sample-rate", type=float, default=250.0, help="fallback sample rate")
    parser.add_argument("--subject-id", default="", help="subject identifier")
    parser.add_argument("--session-id", default="", help="session identifier")
    parser.add_argument("--task-name", default="", help="task/paradigm name")
    args = parser.parse_args()

    input_path = args.input or find_latest_filtered_csv(args.filtered_dir)
    frame, header = read_eeg_table(input_path)
    channel_columns = pick_channel_columns(frame)
    sample_rate_hz = infer_sample_rate(frame, header, args.sample_rate)
    continuous, channels, matrix = normalize_continuous_eeg(
        frame, channel_columns, sample_rate_hz
    )
    events = read_events(args.events, sample_rate_hz)
    metadata = make_metadata(
        input_path, sample_rate_hz, continuous, channels, events, args, header
    )
    workbook_path, matrix_path = write_outputs(
        args.output_dir,
        input_path,
        metadata,
        channels,
        events,
        continuous,
        matrix,
        sample_rate_hz,
    )

    print(f"Input: {input_path}")
    print(f"Samples: {len(continuous)}")
    print(f"Channels: {len(channels)}")
    print(f"Sample rate: {sample_rate_hz:g} Hz")
    print(f"Events: {len(events)}")
    print(f"Workbook: {workbook_path}")
    print(f"Matrix NPZ: {matrix_path}")
    if len(events) == 0:
        print("Events sheet is empty: fill it from the experiment/stimulus log before epoch analysis.")


if __name__ == "__main__":
    main()
